name: CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "website/**"
      - ".github/workflows/website.yml"

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.302"

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --no-build
