name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.302'

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --no-build