name: Publish Release

permissions:
  contents: read

on:
  release:
    types: [ published ]

jobs:
  push-chocolatey:
    if: ${{ vars.ENABLE_CHOCO_PUSH == 'true' }}
    runs-on: windows-latest

    steps:
      - name: Read version
        run: |
          "ver=$($env:GITHUB_REF_NAME -replace '^v', '')" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Download Chocolatey package from release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download "$env:GITHUB_REF_NAME" --pattern "*.nupkg" --repo "${{ github.repository }}"

      - name: Push Chocolatey package
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
        run: |
          choco push "ipatalas-appswitcher.$($env:ver).nupkg" --source https://push.chocolatey.org/ --api-key $env:CHOCO_API_KEY

  trigger-scoop-update:
    if: ${{ vars.ENABLE_SCOOP_UPDATE == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Scoop update workflow
        run: |
          gh workflow run excavator.yml --repo "ipatalas/scoop-bucket" --ref main
        env:
          GH_TOKEN: ${{ secrets.SCOOP_TRIGGER_TOKEN }}

  push-winget:
    if: ${{ vars.ENABLE_WINGET_UPDATE == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: ipatalas.AppSwitcher
          max-versions-to-keep: 5
          token: ${{ secrets.WINGET_GITHUB_TOKEN }}
      - name: Find Dynamic Branch Name
        id: get_branch
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          PATTERN="ipatalas.AppSwitcher-${VERSION}"

          FULL_REF=$(git ls-remote --heads https://${{ secrets.WINGET_FORK_TOKEN }}@github.com/ipatalas/winget-pkgs.git "refs/heads/$PATTERN*" | cut -f2)

          if [ -z "$FULL_REF" ]; then
            echo "Error: Could not find a branch matching $PATTERN"
            exit 1
          fi

          BRANCH_NAME=${FULL_REF#refs/heads/}
          echo "Found branch: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Checkout Specific Branch (Shallow)
        uses: actions/checkout@v4
        with:
          repository: ipatalas/winget-pkgs
          token: ${{ secrets.WINGET_FORK_TOKEN }}
          ref: ${{ steps.get_branch.outputs.branch_name }}
      - name: Fix Manifest
        run: |
          FILE_PATH="manifests/i/ipatalas/AppSwitcher/${{ env.VERSION }}/ipatalas.AppSwitcher.installer.yaml"

          echo "Editing $FILE_PATH on branch $BRANCH_NAME"

          sed -i '/InstallerLocale:/d' "$FILE_PATH"
          sed -i 's/Architecture: x86/Architecture: neutral/g' "$FILE_PATH"

      - name: Push Fixes to Fork
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --staged --quiet; then
            echo "No changes needed."
          else
            git commit -m "Remove InstallerLocale and set Architecture to neutral"
            git push origin HEAD
          fi

  deploy-website:
    uses: ./.github/workflows/website.yml
    secrets: inherit
