name: Release

permissions:
  contents: write

on:
  push:
    tags: [v*]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: v1.0.0
      draft:
        description: 'Create draft release'
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: windows-latest
    env:
      configuration: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Read version - test branch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          version: ${{ inputs.version }}
        run: |
          "ver=$($env:version -replace '^v', '')" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Read version - tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          "ver=$($env:GITHUB_REF_NAME -replace '^v', '')" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Set csproj version
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.6
        with:
          file: "**/*.csproj"
          version: ${{ env.ver }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.302'
          cache: true

      - name: Restore NuGet packages
        run: msbuild /t:Restore /p:Configuration=$env:configuration

      - name: Run tests
        run: dotnet test --no-restore

      - name: Build unpackaged application
        run: msbuild /t:Publish /p:PublishProfile=FolderProfile /p:Configuration=$env:configuration

      - name: Build self-contained application
        run: msbuild /t:Publish /p:PublishProfile=SelfContainedProfile /p:Configuration=$env:configuration

      - name: Create ZIPs
        run: |
          Compress-Archive AppSwitcher/bin/publish/folder/* AppSwitcher-portable.zip
          Compress-Archive AppSwitcher/bin/publish/selfcontained/* AppSwitcher-portable-selfcontained.zip

      - name: Build installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
        with:
          path: AppSwitcher/installer.iss
          options: /DAppVersion=${{ env.ver }}

      - name: Build self-contained installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
        with:
          path: AppSwitcher/installer.iss
          options: |
            /DProfileName=selfcontained
            /DAppVersion=${{ env.ver }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: |
            AppSwitcher-portable.zip
            AppSwitcher-portable-selfcontained.zip
            AppSwitcher/Inno_Files/AppSwitcher Installer.exe
            AppSwitcher/Inno_Files/AppSwitcher Standalone Installer.exe

      - name: Read changelog
        id: changelog
        run: |
            "body<<EOF`n$(.\\extract-changelog.ps1 $env:ver)`nEOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          CHANGES: ${{ steps.changelog.outputs.body }}
        with:
          name: AppSwitcher v${{ env.ver }}
          draft: ${{ inputs.draft }}
          files: |
            AppSwitcher-portable.zip
            AppSwitcher-portable-selfcontained.zip
            AppSwitcher/Inno_Files/AppSwitcher Installer.exe
            AppSwitcher/Inno_Files/AppSwitcher Standalone Installer.exe
          body: ${{ env.CHANGES }}
          make_latest: true

