name: Release

on:
  push:
    tags: [v*]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: v1.0.0-test

jobs:
  release:
    runs-on: windows-latest
    env:
      configuration: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - id: get_version
        name: Get version
        if: startsWith(github.ref, 'refs/tags/')
        uses: jannemattila/get-version-from-tag@v3

      - name: Set version - test branch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          version: ${{ inputs.version }}
        run: |
          "ver=$env:version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Set version - tag
        if: startsWith(github.ref, 'refs/tags/')
        env:
          version: ${{ steps.get_version.outputs.version }}
        run: |
          "ver=$env:version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: msbuild /t:Restore /p:Configuration=$env:configuration

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Build unpackaged application
        run: msbuild /t:Publish /p:PublishProfile=FolderProfile /p:Configuration=$env:configuration
        
      - name: Create ZIP of unpackaged application
        run: Compress-Archive AppSwitcher/bin/publish/folder/* AppSwitcher.zip

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: AppSwitcher
          path: AppSwitcher.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          name: Test release - ${{ env.ver }}
          files: AppSwitcher.zip
          tag_name: ${{ env.ver }}
          release_name: ${{ env.ver }}
          body: |
            Changes in this Release:
            - Initial Test Release
        